### ISSUE TITLE
Yarn silently stops if memory is not enough to start service

### ISSUE THREAD

**Issue by KillWolfVlad** [Byndyusoft/nest-schematics#27]
How to reproduce:

```yaml
version: "3.9"

services:
  app:
    image: some-image:some-tag
    restart: "no"
    mem_reservation: "6M"
    mem_limit: "128M"
    environment:
      SOME_ENV: SOME_ENV_VALUE
```

Solution:

Enable corepack and start service via it.

```Dockerfile
################################################################################

ARG RUNTIME_IMAGE=node:16-bullseye-slim

################################################################################

FROM ${RUNTIME_IMAGE}

RUN corepack enable

WORKDIR /app

COPY . .

USER node
````
